interface FileObj {
  file: string;
  section: string;
  file_type: string;
  text: string;
  file_loc: string;
  folder?: string;
}

interface SummarizedFileObj extends FileObj {
  summary: string;
  isFallback: boolean;
}

/**
 * Given an extracted FileObj, generate a Gemini summary.
 * If no text is found, creates a fallback summary from file name.
 */
export async function summarizeFileObj(obj: any): Promise<SummarizedFileObj> {
  const { file, section, text } = obj;

  // Case 1️⃣: Text available → summarize using Gemini
 
    try {
      const summary = await callGeminiSummary(text, file);
      return {
        ...obj,
        summary,
        isFallback: false,
      };
    } catch (err: any) {
      console.error(`Gemini summarization failed for ${file}: ${err.message}`);
      return {
        ...obj,
        summary: `Summary generation failed for "${file}"`,
        isFallback: true,
      };
    }
}

/**
 * Call Ollama to summarize the text
 */
async function callGeminiSummary(text: string, file: any): Promise<string> {
  const url = "http://localhost:11434/v1/chat/completions";

const prompt = `
You are a helpful summarization assistant.
Summarize the following text concisely in **bullet points**.

If the text is empty, unavailable, or meaningless, 
generate a short summary yourself based on the context of the file name or topic.

---
${text || "No text provided." }

"the file name is " ${file}
---
Instructions:
1️) Provide the summary in bullet/point format.
2️) Keep it concise and clear.
3️) Avoid repetition or long sentences.
`;

  const body = {
    model: "gpt-oss:120b-cloud",
    messages: [{ role: "user", content: prompt }],
  };

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Ollama API error: ${errorText}`);
  }

  const data = await response.json();
  const summary =
    data?.choices?.[0]?.message?.content ||
    "No summary generated by Ollama.";
  return summary.trim();
}
